In [1]:
import pandas as pd
import numpy as np

In [2]:
ability_fp = 'data/charcters_stats.csv'

In [3]:
ability_df = pd.read_csv(ability_fp)

In [13]:
ability_df.loc[ability_df['Name'].apply(lambda x: x.lower()).str.contains('spider')]

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
481,Scarlet Spider,good,75,53,60,74,39,56,357
482,Scarlet Spider II,good,88,55,60,40,30,56,329
515,Spider-Carnage,bad,1,1,1,1,0,1,5
516,Spider-Girl,good,63,38,60,65,46,75,347
517,Spider-Man,good,88,55,60,74,58,85,420
518,Spider-Woman,good,50,42,42,32,62,52,280
519,Spider-Woman II,good,1,1,1,1,0,1,5
520,Spider-Woman III,good,50,48,27,42,60,28,255
521,Spider-Woman IV,bad,1,1,1,1,0,1,5
522,Spiderman,good,1,1,1,1,0,1,5

In [17]:
ability_df_cleaned = ability_df.loc[ability_df['Total'] != 5].reset_index(drop = True)

In [21]:
ability_df_cleaned[ability_df_cleaned['Name'].apply(lambda x: 'spider' in x.lower())]

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
336,Scarlet Spider,good,75,53,60,74,39,56,357
337,Scarlet Spider II,good,88,55,60,40,30,56,329
362,Spider-Girl,good,63,38,60,65,46,75,347
363,Spider-Man,good,88,55,60,74,58,85,420
364,Spider-Woman,good,50,42,42,32,62,52,280
365,Spider-Woman III,good,50,48,27,42,60,28,255

In [22]:
spider_man_stats = ability_df_cleaned.loc[363]

In [23]:
spider_man_stats

Name            Spider-Man
Alignment             good
Intelligence            88
Strength                55
Speed                   60
Durability              74
Power                   58
Combat                  85
Total                  420
Name: 363, dtype: object

In [38]:
mc_fp = 'data/marvel_characters_info.csv'
mc_info = pd.read_csv(mc_fp)
mc_info = mc_info.loc[mc_info['Publisher'] == 'Marvel Comics']

In [39]:
mc_info.head()

,ID,Name,Alignment,Gender,EyeColor,Race,HairColor,Publisher,SkinColor,Height,Weight
0,0,A-Bomb,good,Male,yellow,Human,No Hair,Marvel Comics,-,203.0,441.0
3,3,Abomination,bad,Male,green,Human / Radiation,No Hair,Marvel Comics,-,203.0,441.0
4,4,Abraxas,bad,Male,blue,Cosmic Entity,Black,Marvel Comics,-,-99.0,-99.0
5,5,Absorbing Man,bad,Male,blue,Human,No Hair,Marvel Comics,-,193.0,122.0
8,8,Agent 13,good,Female,blue,-,Blond,Marvel Comics,-,173.0,61.0

In [40]:
ability_df_cleaned.head()

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
0,3-D Man,good,50,31,43,32,25,52,233
1,A-Bomb,good,38,100,17,80,17,64,316
2,Abe Sapien,good,88,14,35,42,35,85,299
3,Abin Sur,good,50,90,53,64,84,65,406
4,Abomination,bad,63,80,53,90,55,95,436

In [59]:
stat_cols = ['Name', 'Alignment', 'Intelligence','Strength','Speed','Durability','Power','Combat','Total']

In [70]:
marvel_info = pd.merge(left=ability_df_cleaned, right=mc_info, on='Name', how='inner').drop('Alignment_y', axis = 1).rename(columns = {'Alignment_x':'Alignment'})
marvel_info.head()

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total,ID,Gender,EyeColor,Race,HairColor,Publisher,SkinColor,Height,Weight
0,A-Bomb,good,38,100,17,80,17,64,316,0,Male,yellow,Human,No Hair,Marvel Comics,-,203.0,441.0
1,Abomination,bad,63,80,53,90,55,95,436,3,Male,green,Human / Radiation,No Hair,Marvel Comics,-,203.0,441.0
2,Abraxas,bad,88,100,83,99,100,56,526,4,Male,blue,Cosmic Entity,Black,Marvel Comics,-,-99.0,-99.0
3,Agent Bob,good,10,8,13,5,5,20,61,9,Male,brown,Human,Brown,Marvel Comics,-,178.0,81.0
4,Agent Zero,good,75,28,38,80,72,95,388,10,Male,-,-,-,Marvel Comics,-,191.0,104.0

In [71]:
marvel_abilities = marvel_info.copy()[stat_cols]
marvel_abilities.head()

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
0,A-Bomb,good,38,100,17,80,17,64,316
1,Abomination,bad,63,80,53,90,55,95,436
2,Abraxas,bad,88,100,83,99,100,56,526
3,Agent Bob,good,10,8,13,5,5,20,61
4,Agent Zero,good,75,28,38,80,72,95,388

In [72]:
average_good_stat = marvel_abilities.loc[marvel_abilities['Alignment'] == 'good'].mean()

In [73]:
average_good_stat

Intelligence     62.220339
Strength         40.271186
Speed            39.067797
Durability       58.717514
Power            55.649718
Combat           63.615819
Total           319.542373
dtype: float64

In [74]:
average_bad_stat = marvel_abilities.loc[marvel_abilities['Alignment'] == 'bad'].mean()

In [75]:
average_bad_stat

Intelligence     64.302632
Strength         47.960526
Speed            37.763158
Durability       65.552632
Power            58.828947
Combat           59.815789
Total           334.223684
dtype: float64

In [82]:
sinister_six = marvel_abilities.loc[marvel_abilities['Name'].apply(lambda x: ('electro' in x.lower()) or ('kraven' in x.lower()) or ('mysterio' in x.lower()) or ('sand' in x.lower()) or ('vulture' in x.lower()))]

In [85]:
sinister_six

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
79,Electro,bad,69,10,50,56,67,64,316
131,Kraven II,bad,50,34,23,28,36,85,256
132,Kraven the Hunter,bad,63,32,35,42,26,85,283
188,Sandman,neutral,50,75,47,97,62,56,387
243,Vulture,bad,63,22,47,56,40,56,284

In [87]:
sinister_six.mean().values

array([ 59. ,  34.6,  40.4,  55.8,  46.2,  69.2, 305.2])

In [86]:
spider_man_stats.index

Index(['Name', 'Alignment', 'Intelligence', 'Strength', 'Speed', 'Durability',
       'Power', 'Combat', 'Total'],
      dtype='object')

### word cloud

In [166]:
txt = ('We need to take the whole line back to formula. Back to formula? Some spiders change colors to blend into their environment. ' +
    'It\'s a defense mechanism.Peter, what makes you think I\'d want to know that?I\'ve been like a father to you. Be a son to me.' +
    'I have a father. His name was Ben Parker.God\'s speed, Spiderman.Let mom and dad talk gobbyWith great power, comes great responsibility.' +
    'The itsy bitsy spider went up the water spout, down came the goblin, and took the spider out.What are you doin up there?' +
    'Staying away from you. That\'s a cute outfit, did your husband get it for you?Who is Spider-man? He\'s a criminal thats who he is.' +
    'What about my uncle? Did you give him a chance? Did you? Did you!?Who are you?Your friendly neighbourhood Spiderman!Your friendly neighborhood Spider-Man!\n' +
    'Your friendly neighbourhood Spiderman! [swings off] Do I get to say thank you this time?with great power comes greater responsibly' +
    'Remember, with great power. comes great responsibility.Who am I? I\'m Spider-Man!You\'re not Superman you know.with great power comes great responsibility.' +
    'I have a father. His name was Ben Parker.With great power, comes great responsibility.Sorry I\'m late. Work was murder.' +
    'If we can get a picture of Julia Roberts in a thong, we can certainly get a picture of this weirdo.' +
    'Whatever life holds in store for me, I will never forget these words: \'With great power, comes great responsibility.\' This is my gift, my curse. Who am I? I\'m Spiderman.'
      ).lower()

In [167]:
print(txt)

we need to take the whole line back to formula. back to formula? some spiders change colors to blend into their environment. it's a defense mechanism.peter, what makes you think i'd want to know that?i've been like a father to you. be a son to me.i have a father. his name was ben parker.god's speed, spiderman.let mom and dad talk gobbywith great power, comes great responsibility.the itsy bitsy spider went up the water spout, down came the goblin, and took the spider out.what are you doin up there?staying away from you. that's a cute outfit, did your husband get it for you?who is spider-man? he's a criminal thats who he is.what about my uncle? did you give him a chance? did you? did you!?who are you?your friendly neighbourhood spiderman!your friendly neighborhood spider-man!
your friendly neighbourhood spiderman! [swings off] do i get to say thank you this time?with great power comes greater responsiblyremember, with great power. comes great responsibility.who am i? i'm spider-man!you're not superman you know.with great power comes great responsibility.i have a father. his name was ben parker.with great power, comes great responsibility.sorry i'm late. work was murder.if we can get a picture of julia roberts in a thong, we can certainly get a picture of this weirdo.whatever life holds in store for me, i will never forget these words: 'with great power, comes great responsibility.' this is my gift, my curse. who am i? i'm spiderman.

In [168]:
import string

In [169]:
txt_clean = txt.translate(str.maketrans(string.punctuation, ' '*len(string.punctuation)))

In [170]:
txt_clean

'we need to take the whole line back to formula  back to formula  some spiders change colors to blend into their environment  it s a defense mechanism peter  what makes you think i d want to know that i ve been like a father to you  be a son to me i have a father  his name was ben parker god s speed  spiderman let mom and dad talk gobbywith great power  comes great responsibility the itsy bitsy spider went up the water spout  down came the goblin  and took the spider out what are you doin up there staying away from you  that s a cute outfit  did your husband get it for you who is spider man  he s a criminal thats who he is what about my uncle  did you give him a chance  did you  did you  who are you your friendly neighbourhood spiderman your friendly neighborhood spider man \nyour friendly neighbourhood spiderman   swings off  do i get to say thank you this time with great power comes greater responsiblyremember  with great power  comes great responsibility who am i  i m spider man you re not superman you know with great power comes great responsibility i have a father  his name was ben parker with great power  comes great responsibility sorry i m late  work was murder if we can get a picture of julia roberts in a thong  we can certainly get a picture of this weirdo whatever life holds in store for me  i will never forget these words   with great power  comes great responsibility   this is my gift  my curse  who am i  i m spiderman '

In [171]:
txt_token = [word.strip() for word in txt_clean.split() if word != '']

In [172]:
import nltk
from nltk.corpus import stopwords

In [173]:
sw =  set(stopwords.words('english'))

In [174]:
important_words = [word for word in txt_token if word not in sw]

In [175]:
pd.Series(important_words).value_counts()[:20].to_dict()

{'great': 11,
 'comes': 6,
 'power': 6,
 'spider': 5,
 'responsibility': 5,
 'get': 4,
 'spiderman': 4,
 'father': 3,
 'friendly': 3,
 'man': 3,
 'ben': 2,
 'formula': 2,
 'name': 2,
 'parker': 2,
 'back': 2,
 'neighbourhood': 2,
 'know': 2,
 'picture': 2,
 'talk': 1,
 'water': 1}

### network

In [176]:
nw_fp = 'data/hero-network.csv'

In [177]:
edges = pd.read_csv(nw_fp)

In [178]:
edges.head()

                  hero1                 hero2
0         LITTLE, ABNER        PRINCESS ZANDA
1         LITTLE, ABNER  BLACK PANTHER/T'CHAL
2  BLACK PANTHER/T'CHAL        PRINCESS ZANDA
3         LITTLE, ABNER        PRINCESS ZANDA
4         LITTLE, ABNER  BLACK PANTHER/T'CHAL

In [179]:
spiderman_immediate = edges.loc[(edges['hero1'] == 'SPIDER-MAN/PETER PAR') | (edges['hero2'] == 'SPIDER-MAN/PETER PAR')]

In [163]:
spiderman_immediate

                       hero1                 hero2
397       NOVA/RICHARD RIDER  SPIDER-MAN/PETER PAR
398     SPIDER-MAN/PETER PAR  FIRESTAR/ANGELICA JO
399     SPIDER-MAN/PETER PAR  THUNDERBALL/DR. ELIO
400     SPIDER-MAN/PETER PAR  NAMORITA/NITA PRENTI
401     SPIDER-MAN/PETER PAR  SPEEDBALL/ROBBIE BAL
402     SPIDER-MAN/PETER PAR  HULK/DR. ROBERT BRUC
403     SPIDER-MAN/PETER PAR  NIGHT THRASHER/DUANE
1505             STACY, PAUL  SPIDER-MAN/PETER PAR
1510             STACY, JILL  SPIDER-MAN/PETER PAR
1514           STACY, ARTHUR  SPIDER-MAN/PETER PAR
1517             PARKER, MAY  SPIDER-MAN/PETER PAR
1518    SPIDER-MAN/PETER PAR     VENOM/EDDIE BROCK
1522                   BLADE  SPIDER-MAN/PETER PAR
1529             STACY, JILL  SPIDER-MAN/PETER PAR
1535     KINGPIN/WILSON FISK  SPIDER-MAN/PETER PAR
1540      LEEDS, BETTY BRANT  SPIDER-MAN/PETER PAR
1541    SPIDER-MAN/PETER PAR        ROBERTSON, JOE
1542    SPIDER-MAN/PETER PAR  FORTUNATO, GIACOMO J
1543    SPIDER-MAN/PETER PAR  MORBIUS/DR. MICHAEL
1548    SPIDER-MAN/PETER PAR  WATSON-PARKER, MARY
1549    SPIDER-MAN/PETER PAR           PARKER, MAY
1550    SPIDER-MAN/PETER PAR          WATSON, ANNA
1578        CALDRONE, JAVIER  SPIDER-MAN/PETER PAR
1591            LUMLEY, JUDY  SPIDER-MAN/PETER PAR
1603      LEEDS, BETTY BRANT  SPIDER-MAN/PETER PAR
1614         MAXWELL, MORRIS  SPIDER-MAN/PETER PAR
1624     THORSON, DR. WALTER  SPIDER-MAN/PETER PAR
1625    SPIDER-MAN/PETER PAR     JAMESON, J. JONAH
1626    SPIDER-MAN/PETER PAR                DOLMAN
1627    SPIDER-MAN/PETER PAR            URICH, BEN
...                      ...                   ...
571380  SPIDER-MAN/PETER PAR  WATSON-PARKER, MARY
571381  SPIDER-MAN/PETER PAR  MYSTERIO/QUENTIN BEC
571382  SPIDER-MAN/PETER PAR  DR. OCTOPUS/OTTO OCT
571383  SPIDER-MAN/PETER PAR    ELECTRO/MAX DILLON
571384  SPIDER-MAN/PETER PAR       SWANN, DR. EVAN
574156  DR. STRANGE/STEPHEN   SPIDER-MAN/PETER PAR
574181   GYRICH, HENRY PETER  SPIDER-MAN/PETER PAR
574205   COOPER, DR. VALERIE  SPIDER-MAN/PETER PAR
574228          STARFOX/EROS  SPIDER-MAN/PETER PAR
574250            KULAN GATH  SPIDER-MAN/PETER PAR
574271  NIGHTCRAWLER/KURT WA  SPIDER-MAN/PETER PAR
574291  SUNSPOT/ROBERTO DACO  SPIDER-MAN/PETER PAR
574310  STORM/ORORO MUNROE S  SPIDER-MAN/PETER PAR
574328  MIRAGE II/DANIELLE M  SPIDER-MAN/PETER PAR
574345                SUNDER  SPIDER-MAN/PETER PAR
574346  SPIDER-MAN/PETER PAR               ROGUE /
574347  SPIDER-MAN/PETER PAR              CALIBAN/
574348  SPIDER-MAN/PETER PAR              CALLISTO
574349  SPIDER-MAN/PETER PAR  COLOSSUS II/PETER RA
574350  SPIDER-MAN/PETER PAR                SELENE
574351  SPIDER-MAN/PETER PAR  PROFESSOR X/CHARLES
574352  SPIDER-MAN/PETER PAR  PHOENIX III/RACHEL S
574353  SPIDER-MAN/PETER PAR  WASP/JANET VAN DYNE
574354  SPIDER-MAN/PETER PAR  CANNONBALL II/SAM GU
574355  SPIDER-MAN/PETER PAR  WOLFSBANE/RAHNE SINC
574356  SPIDER-MAN/PETER PAR  MAGMA/AMARA AQUILLA/
574357  SPIDER-MAN/PETER PAR  SCARLET WITCH/WANDA
574358  SPIDER-MAN/PETER PAR  MAGIK/ILLYANA RASPUT
574359  SPIDER-MAN/PETER PAR       CAPTAIN AMERICA
574360  SPIDER-MAN/PETER PAR           WARLOCK III

[13717 rows x 2 columns]

In [161]:
edges.loc[(edges['hero1'] == 'BLADE') & (edges['hero2'] == 'SPIDER-MAN/PETER PAR')]

       hero1                 hero2
1522   BLADE  SPIDER-MAN/PETER PAR
17918  BLADE  SPIDER-MAN/PETER PAR

In [164]:
edges.loc[(edges['hero1'] == 'SPIDER-MAN/PETER PAR') & (edges['hero2'] == 'BLADE')]

                       hero1  hero2
471647  SPIDER-MAN/PETER PAR  BLADE